### ISSUE TITLE
openai无法使用

### ISSUE THREAD

**Issue by jinghuashang** [hsyhhssyy/amiyabot-hsyhhssyy-chatgpt#1]
2023-02-04 22:56:33,177MiraiINFOBot:1476475122 Channel:6080 User:34 jinghuashang: 你来自哪里？ 
2023-02-04 22:56:33,211BotERRORhandler error: Traceback (most recent call last): 
  File "/home/ubuntu/.local/lib/python3.8/site-packages/amiyabot/log/manager.py", line 100, in catch 
    yield 
  File "/home/ubuntu/.local/lib/python3.8/site-packages/amiyabot/__init__.py", line 67, in __message_handler 
    await message_handler(self, data) 
  File "/home/ubuntu/.local/lib/python3.8/site-packages/amiyabot/factory/messageHandler.py", line 57, in message_handler 
    reply = await handler.action(data) 
  File "/home/ubuntu/.local/lib/python3.8/site-packages/amiyabot/factory/messageHandlerDefine.py", line 138, in action 
    return await self.function(data) 
  File "/home/ubuntu/Amiya-Bot/plugins/amiyabot-hsyhhssyy-chatgpt-1_2/main.py", line 116, in _ 
    request_text = format_request(data.text_origin) 
AttributeError: 'Message' object has no attribute 'text_origin'

**Comment by hsyhhssyy** [comment]
新的1.3版本已经修复了这个问题，您可以试着升级。
