### ISSUE TITLE
向兔兔提问时报错

### ISSUE THREAD

**Issue by desktop4025** [hsyhhssyy/amiyabot-hsyhhssyy-chatgpt#13]
2023-07-22 18:16:22,283 [ ChatGPT][    INFO] proxy set: http://localhost:7890
2023-07-22 18:16:22,286 [ ChatGPT][    INFO] base_url: http://api.openai.com/v1 proxy: http://localhost:7890 model: gpt-3.5/4 Mixed
2023-07-22 18:16:22,881 [ ChatGPT][    INFO] Exception: Only POST requests are accepted. {
    "error": {
        "message": "Only POST requests are accepted.",
        "type": "invalid_request_error",
        "param": null,
        "code": "method_not_supported"
    }
}
 405 {'error': {'message': 'Only POST requests are accepted.', 'type': 'invalid_request_error', 'param': None, 'code': 'method_not_supported'}} {'Date': 'Sat, 22 Jul 2023 10:16:22 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '183', 'Connection': 'keep-alive', 'vary': 'Origin', 'x-request-id': '6b40c222c061f6849b7a256c1392d8e0', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '7eaaed859c88264a-NRT', 'alt-svc': 'h3=":443"; ma=86400'}
2023-07-22 18:16:22,886 [    Main][   ERROR] handler error: Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\site-packages\amiyabot\log\manager.py", line 117, in catch
    yield
  File "C:\ProgramData\anaconda3\lib\site-packages\amiyabot\__init__.py", line 73, in __message_handler
    await message_handler(self, data)
  File "C:\ProgramData\anaconda3\lib\site-packages\amiyabot\handler\messageHandler.py", line 70, in message_handler
    reply = await handler.action(data)
  File "C:\ProgramData\anaconda3\lib\site-packages\amiyabot\factory\implemented.py", line 100, in action
    return await self.function(data)
  File "D:\Git\Amiya-Bot\plugins\amiyabot-hsyhhssyy-chatgpt-3_3_1\main.py", line 152, in _
    await context.on_message(data,request_text,prefixed_call)
  File "D:\Git\Amiya-Bot\plugins\amiyabot-hsyhhssyy-chatgpt-3_3_1\src\ask_amiya.py", line 94, in on_message
    await data.send(Chain(data, reference=True).text(amiya_answer))
  File "C:\ProgramData\anaconda3\lib\site-packages\amiyabot\builtin\messageChain\__init__.py", line 69, in text
    if re.findall(r'\[cl\s(.*?)@#(.*?)\scle]', text):
  File "C:\ProgramData\anaconda3\lib\re.py", line 240, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object

**Comment by hsyhhssyy** [comment]
是每次问问题都会出这个bug吗? 还是只有有时候出? 看起来像是proxy的模式不对? 不行你找个反代试一下?

**Comment by desktop4025** [comment]
> 是每次问问题都会出这个bug吗? 还是只有有时候出? 看起来像是proxy的模式不对? 不行你找个反代试一下?

对，最近一直不行，检查了账号没过期，代理可以连上官网，但不知道能不能连上api。。，我试了开代理和不开代理都不行，我去试试反代，这个不是很了解

**Comment by hsyhhssyy** [comment]
我已经找到原因了，就是网络问题，以前的兔兔遇到网络问题会报错而不是触发一个可读回复，现在我修改了代码，再遇到网络问题，就会返回一句话告诉大家遇到了网络问题。

至于你的问题，大概是你的代理有问题，转发请求的时候弄错了，你可以试试反向代理，或者再调调你的代理。

**Comment by desktop4025** [comment]
> 我已经找到原因了，就是网络问题，以前的兔兔遇到网络问题会报错而不是触发一个可读回复，现在我修改了代码，再遇到网络问题，就会返回一句话告诉大家遇到了网络问题，我发布了新版3.4.3，你可以更新一下。
> 
> 至于你的问题，大概是你的代理有问题，转发请求的时候弄错了，你可以试试反向代理，或者再调调你的代理。

好的谢谢

**Comment by desktop4025** [comment]
更新后成功了，但是显示没有3.5/4mix的模型，换了模型就可以了

>

**Comment by desktop4025** [comment]
> 我已经找到原因了，就是网络问题，以前的兔兔遇到网络问题会报错而不是触发一个可读回复，现在我修改了代码，再遇到网络问题，就会返回一句话告诉大家遇到了网络问题，我发布了新版3.4.3，你可以更新一下。
> 
> 至于你的问题，大概是你的代理有问题，转发请求的时候弄错了，你可以试试反向代理，或者再调调你的代理。

2023-07-25 16:06:17,816 [ ChatGPT][    INFO] base_url: https://api.openai.com/v1 proxy:  model: gpt-3.5/4 Mixed
2023-07-25 16:06:19,350 [ ChatGPT][    INFO] InvalidRequestError: The model `gpt-3.5/4 Mixed` does not exist

**Comment by desktop4025** [comment]
> > 我已经找到原因了，就是网络问题，以前的兔兔遇到网络问题会报错而不是触发一个可读回复，现在我修改了代码，再遇到网络问题，就会返回一句话告诉大家遇到了网络问题，我发布了新版3.4.3，你可以更新一下。
> > 至于你的问题，大概是你的代理有问题，转发请求的时候弄错了，你可以试试反向代理，或者再调调你的代理。
> 
> 2023-07-25 16:06:17,816 [ ChatGPT][ INFO] base_url: https://api.openai.com/v1 proxy: model: gpt-3.5/4 Mixed 2023-07-25 16:06:19,350 [ ChatGPT][ INFO] InvalidRequestError: The model `gpt-3.5/4 Mixed` does not exist

好吧，可能是我账户没有升级

**Comment by hsyhhssyy** [comment]
虽然这其实是另一个bug，但是我建议你还是先手动选3.5的model，因为4很贵很贵。

**Comment by desktop4025** [comment]
> 虽然这其实是另一个bug，但是我建议你还是先手动选3.5的model，因为4很贵很贵。

好的，看了费用，确实贼贵
