### ISSUE TITLE
文心一言角色扮演模式对话出现以下问题 没有回复

### ISSUE THREAD

**Issue by lyt1216** [hsyhhssyy/amiyabot-hsyhhssyy-chatgpt#19]
2024-03-26 21:15:39,038
ChatGPT
INFO
[304509992 ] 模式:角色扮演 消息:兔兔你好啊 
2024-03-26 21:15:44,090
ChatGPT
INFO
[304509992 ]话题改变  -> None interest重置:2000.0 
2024-03-26 21:15:44,092
ChatGPT
INFO
[304509992 ]有Quote/Prefix，强制发话,并切换话题为None 
2024-03-26 21:15:44,101
ChatGPT
INFO
[304509992 ]query_context_index: 0 
2024-03-26 21:15:44,105
ChatGPT
INFO
[304509992 ]使用模型: {'model_name': 'ERNIE-Bot 4.0', 'type': 'high-cost', 'max_token': 4000, 'max-token': 4000, 'supported_feature': ['completion_flow', 'chat_flow', 'json_mode']} 
2024-03-26 21:15:44,107
ChatGPT
INFO
[304509992 ]template select: {'model_name': 'ERNIE-Bot 4.0', 'type': 'high-cost', 'max_token': 4000, 'max-token': 4000, 'supported_feature': ['completion_flow', 'chat_flow', 'json_mode']} deep-cosplay/amiya-template-v5.txt 
2024-03-26 21:15:44,112
ChatGPT
INFO
[304509992 ]加入最多2142字的memory，WordCount是100/0 
2024-03-26 21:15:44,115
ChatGPT
INFO
[304509992 ]ChatGPT Max Retry: 1 
2024-03-26 21:15:44,124
ChatGPT
INFO
[304509992 ]Unknown Error string indices must be integers  
 Traceback (most recent call last): 
  File "/root/Amiya-Bot/plugins/amiyabot-hsyhhssyy-chatgpt-4_1_1/src/deep_cosplay.py", line 488, in get_amiya_response 
    json_str = await self.blm_lib.chat_flow( 
  File "/root/Amiya-Bot/plugins/amiyabot-blm-library-1_2_1/src/common/blm_plugin_instance.py", line 134, in chat_flow 
    return await adapter.chat_flow(prompt, model, context_id, channel_id, functions, json_mode) 
  File "/root/Amiya-Bot/plugins/amiyabot-blm-library-1_2_1/src/ernie/ernie_adapter.py", line 218, in chat_flow 
    prompt = list(filter(prompt_filter, prompt)) 
  File "/root/Amiya-Bot/plugins/amiyabot-blm-library-1_2_1/src/ernie/ernie_adapter.py", line 213, in prompt_filter 
    if item["type"] == "image_url": 
TypeError: string indices must be integers

**Comment by hsyhhssyy** [comment]
已经修改官方插件 大语言模型调用库 里的一处bug，等兔妈更新插件。

你勾选 AI视觉 了吗 目前你也许可以通过切换这个配置项开关尝试规避问题，不过根本来说还是最好等插件更新。

**Comment by hsyhhssyy** [comment]
现在好了吗？
